name: Continuous Deployment
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Check build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [11.x]
    steps:
      - uses: actions/checkout@v1
      - name: Use node @ ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install pkgs
        run: npm install
      - name: Deploy to GH pages
        uses: JamesIves/github-pages-deploy-action@master
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BASE_BRANCH: master
          BRANCH: gh-pages
          FOLDER: dist
          BUILD_SCRIPT: npm install && npm rebuild node-sass && npm run build-dev
